# Generated by Django 3.1.2 on 2021-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='the thao', max_length=255),
            preserve_default=False,
        ),
    ]
