# Generated by Django 3.1.2 on 2021-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_articles_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='hot_score',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
